# Generated by Django 4.2.9 on 2026-03-22 13:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_publicbookingrequest'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermembership',
            name='amount_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customermembership',
            name='amount_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='customermembership',
            name='total_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='plan_type',
            field=models.CharField(choices=[('session', 'Session-based'), ('amount', 'Amount-based')], default='session', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='total_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customermembership',
            name='sessions_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermembership',
            name='sessions_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='total_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipredemption',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='membershipredemption',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
