# Generated by Django 4.2.9 on 2026-03-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_referral_code_and_more'),
        ('appointments', '0002_publicbookingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirm', 'Booking Confirmation'), ('reminder_1hr', 'Reminder (1 Hour)'), ('review_request', 'Review Request'), ('campaign', 'Campaign'), ('referral_welcome', 'Referral Welcome')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer')),
            ],
            options={
                'verbose_name': 'WhatsApp Notification',
                'verbose_name_plural': 'WhatsApp Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
